name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow PyPDF2 pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "ImagePDFProcessor" image_pdf_processor.py

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: ImagePDFProcessor-Windows
        path: dist/ImagePDFProcessor.exe
        retention-days: 5